import { europaGrotesk } from "@/components/CoverVideo";
import "./globals.css";
import { Sirin_Stencil } from "next/font/google";

export const sirinStencil = Sirin_Stencil({
  subsets: ["latin"],
  weight: "400",
});
// export const metadata = {
//   title: "Chicity-Fashion Brand",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Chicity-Fashion Brand</title>
        <meta
          name="description"
          content="Experience the allure of cutting-edge design on our fashion brand's animated site. Immerse yourself in a seamless journey with Lenis scroll, enriched by captivating text animations powered by Framer Motion. Elevate your browsing with mesmerizing parallax effects and scroll animations courtesy of GSAP. Styled to perfection with Tailwind CSS and built for performance with SSR on NextJS. This site is not just a showcase—it's a visual masterpiece, where technology meets style."
        />
      </head>
      <body className={europaGrotesk.className}>{children}</body>
    </html>
  );
}
